name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  DEPLOYMENT_FILE: app.yaml
  DEPLOYMENT_REPO: 
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/my-image:${{ env.IMAGE_TAG }}

      - name: Check out deployment repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEPLOYMENT_REPO }}
          path: deployment-repo

      - name: Update deployment file
        run: |
          cd deployment-repo
          sed -i "s|image:.*|image: ${{ env.DOCKERHUB_USERNAME }}/my-image:${{ env.IMAGE_TAG }}|" ${{ env.DEPLOYMENT_FILE }}

      - name: Commit and push changes to deployment repository
        run: |
          cd deployment-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ${{ env.DEPLOYMENT_FILE }}
          git commit -m "Update image tag"
          git push

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      - name: Authenticate to Google Cloud SDK
        run: gcloud auth login --brief --cred-file="${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Get Kubernetes credentials
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone=${{ env.GKE_ZONE }} --project=${{ env.GKE_PROJECT }}

      - name: Deploy to Kubernetes cluster
        run: kubectl apply -f deployment-repo/${{ env.DEPLOYMENT_FILE }}
