name: Build, Push

on: [pull_request]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: reactjsapp
  IMAGE_TAG: latest
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  DEPLOYMENT_FILE: app.yaml
  DEPLOYMENT_REPO: zefirnikolov/ops-part-deploy-to-gke

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies and Build the app
        run: |
          npm ci
          npm run build

      # - name: Run tests
      #   run: npm run test

      - name: Set image tag based on timestamp
        run: echo "IMAGE_TAG=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Check out deployment repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEPLOYMENT_REPO }}
          path: deployment-repo
          token: ${{ secrets.DEP }}

      - name: Update deployment file
        run: |
          cd deployment-repo
          sed -i "s|image:.*|image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" ${{ env.DEPLOYMENT_FILE }}

      - name: Commit and push changes to deployment repository
        run: |
          cd deployment-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@bot.com"
          git add ${{ env.DEPLOYMENT_FILE }}
          git commit -m "Update image tag"
          git push

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GKE_PROJECT }}

      - name: Authenticate to Google Cloud SDK
        uses: google-github-actions/auth@v0.8.3
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Authenticate to Google Cloud SDK
        run: gcloud auth login --brief --cred-file="${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Install kubectl and gke-gcloud-auth-plugin
        run: |
          gcloud components install kubectl gke-gcloud-auth-plugin

      - name: Get Kubernetes credentials
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone=${{ env.GKE_ZONE }} --project=${{ env.GKE_PROJECT }}

      - name: Deploy to Kubernetes cluster
        run: kubectl apply -f deployment-repo/${{ env.DEPLOYMENT_FILE }}
